#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-retype
Version  : 22.8.0
Release  : 56
URL      : https://files.pythonhosted.org/packages/98/92/1f2522b9e9d264b3fc5b72e14790506e38ac592efda338c63e4cd2e36bf4/retype-22.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/98/92/1f2522b9e9d264b3fc5b72e14790506e38ac592efda338c63e4cd2e36bf4/retype-22.8.0.tar.gz
Summary  : re-apply types from .pyi stub files to your codebase
Group    : Development/Tools
License  : MIT
Requires: pypi-retype-bin = %{version}-%{release}
Requires: pypi-retype-license = %{version}-%{release}
Requires: pypi-retype-python = %{version}-%{release}
Requires: pypi-retype-python3 = %{version}-%{release}
Requires: pypi(pathspec)
Requires: pypi(typed_ast)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(typed_ast)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# retype
**!!! Note this project is no longer supported/maintained as of 2022 August 14th !!!**

%package bin
Summary: bin components for the pypi-retype package.
Group: Binaries
Requires: pypi-retype-license = %{version}-%{release}

%description bin
bin components for the pypi-retype package.


%package license
Summary: license components for the pypi-retype package.
Group: Default

%description license
license components for the pypi-retype package.


%package python
Summary: python components for the pypi-retype package.
Group: Default
Requires: pypi-retype-python3 = %{version}-%{release}

%description python
python components for the pypi-retype package.


%package python3
Summary: python3 components for the pypi-retype package.
Group: Default
Requires: python3-core
Provides: pypi(retype)
Requires: pypi(click)
Requires: pypi(pathspec)
Requires: pypi(typed_ast)

%description python3
python3 components for the pypi-retype package.


%prep
%setup -q -n retype-22.8.0
cd %{_builddir}/retype-22.8.0
pushd ..
cp -a retype-22.8.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695160819
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-retype
cp %{_builddir}/retype-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-retype/f037b5ef1125b5a7f79d85910c7ae8ee6955df7b || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/retype

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-retype/f037b5ef1125b5a7f79d85910c7ae8ee6955df7b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
